sudo: required
language: ruby
services:
  - docker
install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
  - sudo apt-get install cabal-install
  - cabal update
  - cabal install shellcheck
  - sudo apt-get install unzip
  - wget https://releases.hashicorp.com/packer/1.5.4/packer_1.5.4_linux_amd64.zip
  - sudo unzip -o packer_1.5.4_linux_amd64.zip -d /usr/local/bin/
script:
  - make ci
