---
- hosts: localhost

  vars:
    # Available versions: https://github.com/andrewrothstein/ansible-node/blob/main/defaults/main.yml
    node_ver: 22.7.0

  roles:
    - andrewrothstein.node

  tasks:

    - community.general.npm:
        name: bob
        global: true

    - name: Create symbolic link for easy access to node binaries on environments which override the PATH
      ansible.builtin.file:
        src: "/usr/local/node-v{{ node_ver }}-linux-x64"
        dest: /usr/local/node
        state: link