---
- name: Provision Java tools and libraries
  hosts: localhost

  vars:
    # Available versions: https://github.com/andrewrothstein/ansible-maven/blob/main/defaults/main.yml
    maven_ver:
      major: 3
      minor: 9
      patch: 9

  roles:
    - andrewrothstein.maven
