---
- hosts: localhost

  tasks:

    - ansible.builtin.apt:
        update_cache: true
        name: python3-venv
        state: present
        force_apt_get: true

    - community.general.pipx:
        name: "{{ item }}"
        state: latest
      with_items:
        - virtualenv

    - ansible.builtin.get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip"
        dest: /tmp/awscliv2.zip

    - ansible.builtin.unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: true

    - ansible.builtin.command: /tmp/aws/install --update
