---
- hosts: localhost

  vars:
    go_ver: 1.23.0
    hashi_apps:
      - name: packer
        ver: 1.11.2
      - name: terraform
        ver: 1.9.5
    # Available versions: https://github.com/andrewrothstein/ansible-tflint/blob/main/defaults/main.yml
    tflint_ver: v0.53.0
    # Available versions: https://github.com/andrewrothstein/ansible-trivy/blob/main/defaults/main.yml
    trivy_ver: 0.53.0

  roles:
    - andrewrothstein.go
    - andrewrothstein.hashi
    - andrewrothstein.tflint
    - andrewrothstein.trivy

  tasks:

    - ansible.builtin.command: go install github.com/checkmake/checkmake/cmd/checkmake@latest
    - ansible.builtin.command: brew minamijoyo/hcledit/hcledit
