---
- hosts: localhost

  tasks:

    - ansible.builtin.apt:
        pkg:
          - python3-venv

    - community.general.pipx:
        name: "{{ item }}"
        state: latest
      with_items:
        - awscli
        - virtualenv
