---
- name: Provision Python tools and libraries
  hosts: localhost

  tasks:

    - name: Install python3-venv
      ansible.builtin.apt:
        update_cache: true
        name: python3-venv
        state: present
        force_apt_get: true

    - name: Install pipx packages
      community.general.pipx:
        name: "{{ item }}"
        state: latest
      with_items:
        - virtualenv

    - name: Download AWS CLI installer
      ansible.builtin.get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip"
        dest: /tmp/awscliv2.zip
        mode: '0644'

    - name: Extract AWS CLI installer
      ansible.builtin.unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: true

    - name: Install AWS CLI
      ansible.builtin.command: /tmp/aws/install --update
      changed_when: true
