---
- hosts: localhost

  tasks:

    - ansible.builtin.apt:
        pkg:
          - python3-venv

    - vars:
        pipx_pkg:
          - awscli
          - virtualenv
      community.general.pipx:
        name: "{{ item }}"
        state: latest
      with_items: "{{ pipx_pkg }}"
