---
- name: Provision Go tools and libraries
  hosts: localhost

  vars:
    env_path: ''
    go_ver: 1.26.0
    hashi_apps:
      - name: packer
        ver: 1.16.0
      - name: terraform
        ver: 1.15.8
    # Available versions: https://github.com/andrewrothstein/ansible-tflint/blob/main/defaults/main.yml
    tflint_ver: v0.63.1
    # Available versions: https://github.com/andrewrothstein/ansible-trivy/blob/main/defaults/main.yml
    trivy_ver: 0.72.0

  roles:
    - andrewrothstein.go
    - andrewrothstein.hashi
    - andrewrothstein.tflint
    - andrewrothstein.trivy

  tasks:

    - name: Install checkmake
      ansible.builtin.command: go install github.com/checkmake/checkmake/cmd/checkmake@latest
      changed_when: true

    - name: Install hcledit
      ansible.builtin.command: brew install minamijoyo/hcledit/hcledit
      environment:
        PATH: "{{ env_path }}:{{ ansible_env.PATH }}"
      changed_when: true
