---
- hosts: localhost

  vars:
    env_path: ''
    go_ver: 1.23.0
    hashi_apps:
      - name: packer
        ver: 1.14.2
      - name: terraform
        ver: 1.13.4
    # Available versions: https://github.com/andrewrothstein/ansible-tflint/blob/main/defaults/main.yml
    tflint_ver: v0.56.0
    # Available versions: https://github.com/andrewrothstein/ansible-trivy/blob/main/defaults/main.yml
    trivy_ver: 0.60.0

  roles:
    - andrewrothstein.go
    - andrewrothstein.hashi
    - andrewrothstein.tflint
    - andrewrothstein.trivy

  tasks:

    - ansible.builtin.command: go install github.com/checkmake/checkmake/cmd/checkmake@latest
    - ansible.builtin.shell: brew install minamijoyo/hcledit/hcledit
      environment:
        PATH: "{{ env_path }}:{{ ansible_env.PATH }}"
