---
- name: Provision common tools and libraries
  hosts: localhost

  tasks:

    - name: Create local bin directory
      ansible.builtin.file:
        path: /root/.local/bin
        state: directory
        mode: '0755'
