#!/bin/sh
set -o errexit
set -o nounset

export PATH=$ENV_PATH:$PATH

echo "****************************************"
echo "* Provisioned software info - Post"
echo "****************************************"
echo "PATH: $PATH"
echo "aws version: $(aws --version)"
echo "bob version: $(bob --version)"
echo "brew version: $(brew --version)"
echo "checkmake version: $(checkmake --version)"
echo "cyclonedx version: $(cyclonedx --version)"
echo "gem version: $(gem --version)"
echo "gemini version: $(gemini --version)"
echo "hcledit version: $(hcledit version)"
echo "java version: $(java --version)"
echo "jq version: $(jq --version)"
echo "mvn version: $(mvn --version)"
echo "netstat version: $(netstat --version)"
echo "node version: $(node --version)"
echo "npm version: $(npm --version)"
echo "npx version: $(npx --version)"
echo "packer version: $(packer --version)"
echo "ruby version: $(ruby --version)"
echo "rustc version: $(rustc --version)"
echo "rustup version: $(rustup --version)"
echo "shellcheck version: $(shellcheck --version)"
echo "telnet version: $(telnet --version)"
echo "terraform version: $(terraform --version)"
echo "tflint version: $(tflint --version)"
echo "trivy version: $(trivy --version)"
echo "vim version: $(vim --version)"
echo "virtualenv version: $(virtualenv --version)"
echo "yq version: $(yq --version)"
echo "zip version: $(zip --version)"
