---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        set-safe-directory: ${{ github.workspace }}
    - name: Free disk space on GH runner
      run: |
        docker system prune -af
        docker volume prune -f
        sudo rm -rf /usr/local/lib/android /opt/ghc /usr/share/dotnet /usr/local/share/boost
        sudo apt-get clean
    - uses: cliffano/command-docker-action@v1.2.0
      with:
        image: cliffano/studio:1.15.0
        command: 'make ci'