---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          set-safe-directory: ${{ github.workspace }}
      - uses: cliffano/command-docker-action@v2.0.0
        with:
          image: cliffano/studio:3.2.0
          command: 'make deps ci'
