---
name: Publish Docker Studio
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          ref: main
      - uses: docker/login-action@v4
        with:
          username: cliffano
          password: ${{ secrets.STUDIO_DOCKERHUB_TOKEN }}
      - uses: cliffano/command-docker-action@v2.1.0
        with:
          image: cliffano/studio:3.2.0
          shell: bash
          extra_args: '-v ~/.docker/config.json:/root/.docker/config.json:ro'
          command: >
            make clean stage deps lint build-docker-studio && cat
            logs/packer-docker-studio.log && docker --version && docker info  &&
            docker inspect cliffano/studio && make publish-docker-studio
